spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql:http://localhost:5454/postgres
    username: admin
    password: 123456789
    name: user_db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registery: true
