spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/my-tiny-library/config-server/configs
          search-paths: '{application}'

server:
  port: 8888
